"""scores relationship added

Revision ID: 1549029f30c2
Revises: 1604db4e9b29
Create Date: 2022-05-13 19:04:31.057216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1549029f30c2'
down_revision = '1604db4e9b29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scores', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('scores', 'word_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scores', 'word_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('scores', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
