"""difficulty and date from utc

Revision ID: 756bb83fd956
Revises: 84a0e7466310
Create Date: 2022-05-22 15:19:37.680205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '756bb83fd956'
down_revision = '84a0e7466310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('difficulty', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scores', 'difficulty')
    # ### end Alembic commands ###
